# Generated by Django 3.1.7 on 2021-05-05 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Nazwa programu')),
                ('description', models.CharField(max_length=128, null=True, verbose_name='Opis programu')),
                ('set_manual', models.BooleanField(default=False, verbose_name='Uruchom ręcznie')),
                ('running', models.BooleanField(default=False, verbose_name='Aktualnie wykonywany')),
                ('active', models.BooleanField(default=True, verbose_name='Aktywny')),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': '5 Programy',
                'ordering': ['active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProgStartTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='Nazwa startu')),
                ('description', models.CharField(max_length=32, null=True, verbose_name='Opis startu')),
                ('day_delay', models.PositiveSmallIntegerField(default=0, verbose_name='Ilość dni przerwy')),
                ('start_time', models.TimeField(default='07:00:00', verbose_name='Godzina uruchomienia')),
                ('stop_time', models.TimeField(default='07:30:00', verbose_name='Godzina zakończenia')),
                ('next_time', models.DateTimeField(null=True, verbose_name='Następny start')),
                ('running', models.BooleanField(default=False, verbose_name='Uruchomiony')),
                ('active', models.BooleanField(default=True, verbose_name='Aktywny')),
                ('prog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progstarts', to='programs.progname', verbose_name='Dla programu')),
            ],
            options={
                'verbose_name': 'Program - pory uruchomień',
                'verbose_name_plural': '7 Programy - pory uruchomień',
                'ordering': ['next_time', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProgPinCfg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lp', models.PositiveSmallIntegerField(default=0, verbose_name='Kolejność')),
                ('duration_time', models.TimeField(default='00:00:01', verbose_name='Czas pracy')),
                ('stop_time', models.TimeField(default='00:00:00', verbose_name='Czas zakończenia działania')),
                ('parallel', models.BooleanField(default=False, verbose_name='Praca równoległa do końca programu')),
                ('set_on', models.BooleanField(default=False, null=True, verbose_name='Włącz')),
                ('set_off', models.BooleanField(default=False, null=True, verbose_name='Wyłącz')),
                ('active', models.BooleanField(default=True, verbose_name='Dostępność')),
                ('pin_cfg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gpiopins', to='items.gpiopincfg', verbose_name='Pin sterujący')),
                ('prog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progpin', to='programs.progname', verbose_name='Dla programu')),
            ],
            options={
                'ordering': ['prog', 'lp'],
                'unique_together': {('prog', 'pin_cfg', 'lp')},
            },
        ),
    ]
