# Generated by Django 3.1.7 on 2021-04-13 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Nazwa programu')),
                ('description', models.CharField(max_length=48, null=True, verbose_name='Opis programu')),
                ('active', models.BooleanField(default=True, verbose_name='Aktywny')),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': '5 Programy',
                'ordering': ['active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProgStartTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='Nazwa startu')),
                ('description', models.CharField(max_length=32, null=True, verbose_name='Opis startu')),
                ('day_delay', models.PositiveSmallIntegerField(default=0, verbose_name='Ilość dni przerwy')),
                ('start_time', models.TimeField(default='07:00:00', verbose_name='Godzina uruchomienia')),
                ('active', models.BooleanField(default=True, verbose_name='Aktywny')),
                ('prog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.progname', verbose_name='Dla programu')),
            ],
            options={
                'verbose_name': 'Program - pory uruchomień',
                'verbose_name_plural': '7 Programy - pory uruchomień',
                'ordering': ['start_time', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProgPinCfg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lp', models.PositiveSmallIntegerField(default=0, verbose_name='Kolejność')),
                ('duration_sec', models.PositiveSmallIntegerField(default=1, verbose_name='Czas trwania [s]')),
                ('pin_cfg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.gpiopincfg', verbose_name='Pin sterujący')),
                ('prog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.progname', verbose_name='Dla programu')),
            ],
            options={
                'verbose_name': 'Program - urządzenia',
                'verbose_name_plural': '6 Programy - urządzenia',
                'ordering': ['lp'],
            },
        ),
    ]
