# Generated by Django 3.1.7 on 2021-04-20 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progpincfg',
            options={'ordering': ['lp']},
        ),
        migrations.AlterField(
            model_name='progpincfg',
            name='prog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progpin', to='programs.progname', verbose_name='Dla programu'),
        ),
        migrations.AlterField(
            model_name='progstarttime',
            name='prog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progstarts', to='programs.progname', verbose_name='Dla programu'),
        ),
        migrations.AlterUniqueTogether(
            name='progpincfg',
            unique_together={('prog', 'lp')},
        ),
    ]
