# Generated by Django 3.1.7 on 2021-04-20 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_auto_20210420_1753'),
        ('programs', '0003_auto_20210420_1243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progpincfg',
            options={'ordering': ['prog', 'lp']},
        ),
        migrations.AddField(
            model_name='progpincfg',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='Dostępność'),
        ),
        migrations.AlterUniqueTogether(
            name='progpincfg',
            unique_together={('prog', 'pin_cfg', 'lp')},
        ),
    ]
