# Generated by Django 3.1.7 on 2021-04-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_auto_20210420_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='progname',
            name='running',
            field=models.BooleanField(default=False, verbose_name='Aktualnie wykonywany'),
        ),
        migrations.AddField(
            model_name='progname',
            name='stop_run',
            field=models.BooleanField(default=False, verbose_name='Przerwanie wykonywania'),
        ),
        migrations.AddField(
            model_name='progpincfg',
            name='parallel',
            field=models.BooleanField(default=False, verbose_name='Praca równoległa do końca programu'),
        ),
    ]
