# Generated by Django 3.1.7 on 2021-04-23 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0005_auto_20210422_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='progstarttime',
            name='next_start',
            field=models.DateTimeField(default='0001-01-01 00:00:00.0', verbose_name='Natępny start'),
        ),
    ]
