# Generated by Django 3.1.7 on 2021-04-23 06:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0008_auto_20210423_0642'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progstarttime',
            options={'ordering': ['next_time', 'name'], 'verbose_name': 'Program - pory uruchomień', 'verbose_name_plural': '7 Programy - pory uruchomień'},
        ),
        migrations.RemoveField(
            model_name='progstarttime',
            name='next_start',
        ),
        migrations.AddField(
            model_name='progstarttime',
            name='next_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 23, 6, 53, 44, 532188), verbose_name='Następny start'),
        ),
    ]
