# Generated by Django 3.1.7 on 2021-04-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0009_auto_20210423_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progstarttime',
            name='next_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Następny start'),
        ),
    ]
