# Generated by Django 3.1.7 on 2021-04-23 19:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0013_auto_20210423_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='progname',
            name='stop_run',
            field=models.TimeField(default='07:00:00', verbose_name='Czas zakończenia pracy programu'),
        ),
        migrations.AlterField(
            model_name='progpincfg',
            name='stop_time',
            field=models.TimeField(default='19:37:38', verbose_name='Czas zakończenia działania'),
        ),
        migrations.AlterField(
            model_name='progstarttime',
            name='next_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 23, 19, 37, 38, 469439), verbose_name='Następny start'),
        ),
    ]
