# Generated by Django 3.1.7 on 2021-04-23 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0016_auto_20210423_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progpincfg',
            name='stop_time',
            field=models.TimeField(default='00:00:00', verbose_name='Czas zakończenia działania'),
        ),
        migrations.AlterField(
            model_name='progstarttime',
            name='next_time',
            field=models.DateTimeField(default='2021-04-23T19:39:54.620983', verbose_name='Następny start'),
        ),
    ]
