# Generated by Django 3.1.7 on 2021-04-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0021_auto_20210423_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progstarttime',
            name='start_time',
        ),
        migrations.AddField(
            model_name='progstarttime',
            name='stop_time',
            field=models.TimeField(default='00:00:00', verbose_name='Godzina uruchomienia'),
        ),
        migrations.AlterField(
            model_name='progname',
            name='stop_run',
            field=models.TimeField(default='00:00:00', verbose_name='Czas zakończenia pracy programu'),
        ),
    ]
