# Generated by Django 3.1.7 on 2021-04-23 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0022_auto_20210423_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progstarttime',
            name='stop_time',
        ),
    ]
