# Generated by Django 3.1.7 on 2021-04-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0023_remove_progstarttime_stop_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='progstarttime',
            name='start_time',
            field=models.TimeField(default='07:00:00', verbose_name='Godzina uruchomienia'),
        ),
    ]
