# Generated by Django 3.1.7 on 2021-04-28 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0026_auto_20210424_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='progstarttime',
            name='stop_time',
            field=models.TimeField(default='07:30:00', verbose_name='Godzina zakończenia'),
        ),
    ]
