# Generated by Django 3.1.7 on 2021-05-03 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0027_progstarttime_stop_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progname',
            name='description',
            field=models.CharField(max_length=128, null=True, verbose_name='Opis programu'),
        ),
        migrations.AlterField(
            model_name='progname',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Nazwa programu'),
        ),
    ]
