# Generated by Django 3.1.7 on 2021-05-03 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0028_auto_20210503_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progname',
            name='stop_run',
        ),
    ]
