# Generated by Django 3.1.7 on 2021-05-03 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0029_remove_progname_stop_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='progname',
            name='set_manual',
            field=models.BooleanField(default=False, verbose_name='Uruchom ręcznie'),
        ),
    ]
