# Generated by Django 3.1.7 on 2021-05-03 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0030_progname_set_manual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progpincfg',
            name='duration_sec',
        ),
    ]
