# Generated by Django 3.1.7 on 2021-04-14 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cfgtype',
            name='description',
            field=models.CharField(max_length=64, null=True, verbose_name='Opis polecenia'),
        ),
        migrations.AlterField(
            model_name='cfgtype',
            name='name',
            field=models.CharField(max_length=8, verbose_name='Komenda'),
        ),
    ]
