# Generated by Django 3.1.7 on 2021-04-14 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_auto_20210414_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfgcommand',
            name='description',
            field=models.CharField(max_length=64, null=True, verbose_name='Opis polecenia'),
        ),
    ]
