# Generated by Django 3.1.7 on 2021-04-14 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_cfgcommand_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cfgtype',
            name='name',
            field=models.CharField(max_length=16, verbose_name='Komenda'),
        ),
    ]
