# Generated by Django 3.1.7 on 2021-04-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_auto_20210414_0716'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cfgcommand',
            options={'ordering': ['type__description', 'name'], 'verbose_name': 'Konfiguracja', 'verbose_name_plural': 'Konfiguracja - komendy'},
        ),
        migrations.AlterModelOptions(
            name='cfgtype',
            options={'ordering': ['name'], 'verbose_name': 'Typ komendy', 'verbose_name_plural': 'Konfiguracja - typy komend'},
        ),
        migrations.AlterField(
            model_name='cfgtype',
            name='description',
            field=models.CharField(max_length=64, null=True, verbose_name='Opis typu polecenia'),
        ),
        migrations.AlterField(
            model_name='cfgtype',
            name='name',
            field=models.CharField(max_length=16, verbose_name='Nazwa typu polecenia'),
        ),
    ]
