ITEMS_NAME = [
    ['raspberry', 'mikrokomputer (ARM 11 1GHz 512MB RAM)', 40],
]

BUSS_NAME = [
    ['raspberry', 'GPIO', 'Piny wejścia i wyścia'],
    ['raspberry', 'I2C0', 'Szeregowa szyna danych'],
    ['raspberry', 'I2C1', 'Szeregowa szyna danych'],
    ['raspberry', 'SPI0', 'Szeregowa szyna danych'],
    ['raspberry', 'Supply', 'Złącza zasilania'],
    ['raspberry', 'UART0', 'Szeregowa szyna danych'],
]

BUSS_PIN = [
    ['raspberry', '3V3', 'Zasilanie 3V3', 1, 'Supply'],
    ['raspberry', '5V', 'Zasilanie 5V', 2, 'Supply'],
    ['raspberry', 'SDA1', 'Linia danych', 3, 'I2C1'],
    ['raspberry', 'BOARD3', 'IN/OUT', 3, 'GPIO'],
    ['raspberry', '5V', 'Zasilanie 5V', 4, 'Supply'],
    ['raspberry', 'SCL1', 'Taktowanie', 5, 'I2C1'],
    ['raspberry', 'BOARD5', 'IN/OUT', 5, 'GPIO'],
    ['raspberry', 'GND', 'Masa', 6, 'Supply'],
    ['raspberry', 'BOARD7', 'IN/OUT', 7, 'GPIO'],
    ['raspberry', 'TXD0', 'Nadawanie', 8, 'UART0'],
    ['raspberry', 'BOARD8', 'IN/OUT', 8, 'GPIO'],
    ['raspberry', 'GND', 'Masa', 9, 'Supply'],
    ['raspberry', 'RXD0', 'Odbieranie', 10, 'UART0'],
    ['raspberry', 'BOARD10', 'IN/OUT', 10, 'GPIO'],
    ['raspberry', 'BOARD11', 'IN/OUT', 11, 'GPIO'],
    ['raspberry', 'BOARD12', 'IN/OUT', 12, 'GPIO'],
    ['raspberry', 'BOARD13', 'IN/OUT', 13, 'GPIO'],
    ['raspberry', 'GND', 'Masa', 14, 'Supply'],
    ['raspberry', 'BOARD15', 'IN/OUT', 15, 'GPIO'],
    ['raspberry', 'BOARD16', 'IN/OUT', 16, 'GPIO'],
    ['raspberry', '3V3', 'Zasilanie 3V3', 17, 'Supply'],
    ['raspberry', 'BOARD18', 'IN/OUT', 18, 'GPIO'],
    ['raspberry', 'MOSI0', 'Odbieranie', 19, 'SPI0'],
    ['raspberry', 'BOARD19', 'IN/OUT', 19, 'GPIO'],
    ['raspberry', 'GND', 'Masa', 20, 'Supply'],
    ['raspberry', 'MISO0', 'Nadawanie', 21, 'SPI0'],
    ['raspberry', 'BOARD21', 'IN/OUT', 21, 'GPIO'],
    ['raspberry', 'BOARD22', 'IN/OUT', 22, 'GPIO'],
    ['raspberry', 'CLK0', 'Taktowanie', 23, 'SPI0'],
    ['raspberry', 'BOARD23', 'IN/OUT', 23, 'GPIO'],
    ['raspberry', 'CE0', 'Wybór układu', 24, 'SPI0'],
    ['raspberry', 'BOARD24', 'IN/OUT', 24, 'GPIO'],
    ['raspberry', 'GND', 'Masa', 25, 'Supply'],
    ['raspberry', 'BOARD26', 'IN/OUT', 26, 'GPIO'],
    ['raspberry', 'SDA0', 'Linia danych', 27, 'I2C0'],
    ['raspberry', 'BOARD27', 'IN/OUT', 27, 'GPIO'],
    ['raspberry', 'SCL0', 'Taktowanie', 28, 'I2C0'],
    ['raspberry', 'BOARD28', 'IN/OUT', 28, 'GPIO'],
    ['raspberry', 'BOARD29', 'IN/OUT', 29, 'GPIO'],
    ['raspberry', 'GND', 'Masa', 30, 'Supply'],
    ['raspberry', 'BOARD31', 'IN/OUT', 31, 'GPIO'],
    ['raspberry', 'BOARD32', 'IN/OUT', 32, 'GPIO'],
    ['raspberry', 'BOARD33', 'IN/OUT', 33, 'GPIO'],
    ['raspberry', 'GND', 'Masa', 34, 'Supply'],
    ['raspberry', 'BOARD35', 'IN/OUT', 35, 'GPIO'],
    ['raspberry', 'BOARD36', 'IN/OUT', 36, 'GPIO'],
    ['raspberry', 'BOARD37', 'IN/OUT', 37, 'GPIO'],
    ['raspberry', 'BOARD38', 'IN/OUT', 38, 'GPIO'],
    ['raspberry', 'GND', 'Masa', 39, 'Supply'],
    ['raspberry', 'BOARD40', 'IN/OUT', 40, 'GPIO'],
]

GPIO_PIN_DATA = [
    ['BOARD19', 'Sekcja 1', 'Nawadnianie sekcja 1', 19, True, 0, 0],
    ['BOARD21', 'Sekcja 2', 'Nawadnianie sekcja 2', 21, True, 0, 0],
    ['BOARD21', 'Sekcja 3', 'Nawadnianie sekcja 3', 23, True, 0, 0],
    ['BOARD21', 'Sekcja 4', 'Nawadnianie sekcja 4', 26, True, 0, 0],
    ['BOARD21', 'Sekcja 5', 'Nawadnianie sekcja 5', 29, True, 0, 0],
    ['BOARD21', 'Sekcja 6', 'Nawadnianie sekcja 6', 31, True, 0, 0],
    ['BOARD21', 'Sekcja 7', 'Nawadnianie sekcja 7', 33, True, 0, 0],
    ['BOARD21', 'Sekcja 8', 'Nawadnianie sekcja 8', 35, True, 0, 0],
    ['BOARD21', 'Sensor 1', 'Czujnik deszczu', 32, False, 1, 1],
]
