# Generated by Django 3.1.7 on 2021-04-16 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherlong',
            name='ligh_night_m',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Nasłonecznienie'),
            preserve_default=False,
        ),
    ]
