# Generated by Django 3.1.7 on 2021-05-06 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherdaily',
            name='ligh_m',
            field=models.DecimalField(decimal_places=1, max_digits=7, verbose_name='Nasłonecznienie'),
        ),
        migrations.AlterField(
            model_name='weatherdaily',
            name='pres_m',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Ciśnienie atmosferyczne'),
        ),
    ]
