# Generated by Django 3.1.7 on 2021-04-16 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_weatherlong_ligh_night_m'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_m', models.DateField(verbose_name='Data pomiarów')),
                ('temp_m', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Temperatura')),
                ('pres_m', models.PositiveSmallIntegerField(verbose_name='Ciśnienie atmosferyczne')),
                ('humi_m', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Wilgotność powietrza')),
                ('ligh_m', models.PositiveSmallIntegerField(verbose_name='Nasłonecznienie')),
                ('time_day_start', models.TimeField(verbose_name='Czas rozpoczęcia dnia')),
                ('time_day_stop', models.TimeField(verbose_name='Czas zakończenia dnia')),
                ('temp_day_m', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Temperatura')),
                ('pres_day_m', models.PositiveSmallIntegerField(verbose_name='Ciśnienie atmosferyczne')),
                ('humi_day_m', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Wilgotność powietrza')),
                ('ligh_day_m', models.PositiveSmallIntegerField(verbose_name='Nasłonecznienie')),
                ('temp_night_m', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Temperatura')),
                ('pres_night_m', models.PositiveSmallIntegerField(verbose_name='Ciśnienie atmosferyczne')),
                ('humi_night_m', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Wilgotność powietrza')),
                ('ligh_night_m', models.PositiveSmallIntegerField(verbose_name='Nasłonecznienie')),
            ],
            options={
                'verbose_name': 'Pogoda - średnia tygodniowa',
                'verbose_name_plural': 'Pogoda - średnie tygodniowe',
                'ordering': ['date_m'],
            },
        ),
        migrations.AlterModelOptions(
            name='weatherlong',
            options={'ordering': ['date_m'], 'verbose_name': 'Pogoda - średnia dzienna', 'verbose_name_plural': 'Pogoda - średnie dzienne'},
        ),
    ]
