# Generated by Django 3.1.7 on 2021-05-12 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_auto_20210512_0558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherlong',
            name='rain_day_m',
        ),
        migrations.RemoveField(
            model_name='weatherlong',
            name='rain_night_m',
        ),
    ]
