# Generated by Django 3.1.7 on 2021-05-04 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_auto_20210416_0821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherlong',
            name='humi_day_m',
        ),
        migrations.RemoveField(
            model_name='weatherlong',
            name='humi_m',
        ),
        migrations.RemoveField(
            model_name='weatherlong',
            name='humi_night_m',
        ),
        migrations.RemoveField(
            model_name='weatherlong',
            name='ligh_day_m',
        ),
        migrations.RemoveField(
            model_name='weatherlong',
            name='ligh_m',
        ),
        migrations.RemoveField(
            model_name='weatherlong',
            name='ligh_night_m',
        ),
        migrations.RemoveField(
            model_name='weatherlong',
            name='pres_day_m',
        ),
        migrations.RemoveField(
            model_name='weatherlong',
            name='pres_m',
        ),
        migrations.RemoveField(
            model_name='weatherlong',
            name='pres_night_m',
        ),
        migrations.RemoveField(
            model_name='weatherlong',
            name='temp_day_m',
        ),
        migrations.RemoveField(
            model_name='weatherlong',
            name='temp_m',
        ),
        migrations.RemoveField(
            model_name='weatherlong',
            name='temp_night_m',
        ),
        migrations.RemoveField(
            model_name='weatherlong',
            name='time_day_start',
        ),
        migrations.RemoveField(
            model_name='weatherlong',
            name='time_day_stop',
        ),
    ]
