# Generated by Django 3.1.7 on 2021-05-05 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BussNameType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='Magistrala')),
                ('description', models.CharField(max_length=48, verbose_name='Opis')),
                ('buss_adr', models.CharField(default=None, max_length=8, null=True, verbose_name='Adres komunikacji')),
            ],
            options={
                'verbose_name': 'Magistrala',
                'verbose_name_plural': '2 Magistrale',
                'ordering': ['items_name__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ItemName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='Nazwa sterownika')),
                ('description', models.CharField(max_length=64, verbose_name='Opis')),
                ('num_pin', models.PositiveSmallIntegerField(verbose_name='Ilość pinów IO')),
            ],
            options={
                'verbose_name': 'Sterownik',
                'verbose_name_plural': '1 Sterowniki',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BussPinType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='Nazwa pinu')),
                ('description', models.CharField(max_length=48, verbose_name='Opis pinu')),
                ('pin_board', models.PositiveSmallIntegerField(verbose_name='Numer pinu')),
                ('buss_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.bussnametype', verbose_name='Magistrala')),
                ('items_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.itemname', verbose_name='Urządzenie')),
            ],
            options={
                'verbose_name': 'Magistrala - pin',
                'verbose_name_plural': '3 Magistrale - piny',
                'ordering': ['items_name__name', 'pin_board'],
            },
        ),
        migrations.AddField(
            model_name='bussnametype',
            name='items_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.itemname', verbose_name='Urządzenie'),
        ),
        migrations.CreateModel(
            name='GpioPinCfg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, null=True, verbose_name='Nazwa modułu')),
                ('description', models.CharField(max_length=48, null=True, verbose_name='Opis modułu')),
                ('pin_board', models.PositiveSmallIntegerField(verbose_name='Numer pinu')),
                ('dir_out', models.BooleanField(default=True, verbose_name='Kierunek wyjściowy')),
                ('val', models.PositiveSmallIntegerField(null=True, verbose_name='Stan aktualny')),
                ('val_default', models.PositiveSmallIntegerField(null=True, verbose_name='Wartość domyślna')),
                ('buss_pin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='busspin', to='items.busspintype', verbose_name='IO sterownika')),
            ],
            options={
                'ordering': ['pin_board'],
                'unique_together': {('buss_pin', 'pin_board')},
            },
        ),
    ]
