# Generated by Django 3.1.7 on 2021-04-20 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpiopincfg',
            name='buss_pin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gpio_pins', to='items.busspintype', verbose_name='IO sterownika'),
        ),
    ]
